import PathCompressionDigestion.Basic
import PathCompressionDigestion.Ackermann
import PathCompressionDigestion.Threshold
import PathCompressionDigestion.ThresholdInverse
import PathCompressionDigestion.MainComparison
