import PathCompressionDigestion.Basic
import PathCompressionDigestion.CeilLog2
import PathCompressionDigestion.Ackermann
import PathCompressionDigestion.Threshold
import PathCompressionDigestion.MainComparison
