import PathCompressionDigestion.Basic
import PathCompressionDigestion.JBase
import PathCompressionDigestion.CeilLog2
import PathCompressionDigestion.Diamond
import PathCompressionDigestion.Ackermann
import PathCompressionDigestion.Threshold
import PathCompressionDigestion.ThresholdInverse
import PathCompressionDigestion.MainComparison
